name: Workflow for Python-CI

on:
 pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with Pytest
        run: |
          pip3 install coverage
          pwd && ls -la
          python3 -m coverage run -m unittest src/main/python/helloworld.py 
          python3 -m coverage report
          python3 -m coverage html
          python3 -m coverage xml
          pwd && ls -la
          
      - name: Reject pull request on test failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             gh api repos/pooja03ydv/python-app/branches/smita/protection \
             -f required_status_checks.strict=true \
             -f required_status_checks.contexts=[] \
             -f required_pull_request_reviews.required_approving_review_count=1 \
             -f required_pull_request_reviews.dismiss_stale_reviews=false \
              -f enforce_admins.enabled=true \
             -XPUT


     
          
      - name: Delete pull request on test failure
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
      
          gh pr comment ${{ github.event.pull_request.number }} --body "Test results:<br/>$(cat /home/runner/work/python-app/python-app/coverage.xml)"
          gh pr comment ${{ github.event.pull_request.number }} --body "Test results:<br/>$(cat /home/runner/work/python-app/python-app/htmlcov/index.html)"
          
         

          
      
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
