name: PYTHON CI

on:
 pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with Pytest
        run: |
          pip3 install coverage
          pwd && ls -la
          python3 -m coverage run -m unittest src/main/python/helloworld.py
          python3 -m coverage report
          python3 -m coverage html
          python3 -m coverage xml
      - name: Delete pull request on test failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr lock  "${{ github.event.pull_request.number }}"
      
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
