name: Workflow test

on:
 push:
 workflow_dispatch:

jobs:
          
  python-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          DATA=myname
      - name:  pass input 
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh workflow run "Workflow for Python-CI" --ref features pooja03ydv/python-app -f FILE=$DATA
